# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1XEmFha12TSei2zyKvnNUARGaXmjNEM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pathlib
# import nltk
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
# 
# # -------------------------------------------------
# # 0️⃣ Setup – download VADER lexicon once
# # -------------------------------------------------
# nltk.download('vader_lexicon', quiet=True)
# vader = SentimentIntensityAnalyzer()
# 
# # -------------------------------------------------
# # 1️⃣ Helper: load the CSV (cached for speed)
# # -------------------------------------------------
# @st.cache_data(ttl=86400)   # cache for 24 h
# def load_data(path: str) -> pd.DataFrame:
#     df = pd.read_csv(path, parse_dates=["order_date_time",
#                                         "synthetic_date",
#                                         "Survey_response_Date"])
#     return df
# 
# # -------------------------------------------------
# # 2️⃣ Choose data source – tiny sample shipped with the repo
# # -------------------------------------------------
# data_path = pathlib.Path(__file__).parent / "sample_flagged.csv"
# df = load_data(str(data_path))
# 
# # -------------------------------------------------
# # 3️⃣ UI layout
# # -------------------------------------------------
# st.set_page_config(page_title="SMB Risk Dashboard",
#                    layout="wide",
#                    page_icon="🔍")
# 
# st.title("🔎 SMB Customer‑Sentiment + Transaction Risk Dashboard")
# st.markdown("""
# A lightweight demo that joins **customer remarks** with **synthetic transaction data**, runs **sentiment analysis**, and highlights high‑value, negative‑sentiment cases.
# """)
# 
# # ---- Sidebar filters -------------------------------------------------
# st.sidebar.header("🔧 Filters")
# price_min = st.sidebar.slider("Minimum Transaction Amount ($)",
#                               min_value=0,
#                               max_value=int(df["Item_price"].max()),
#                               value=200,
#                               step=50)
# 
# sentiment_max = st.sidebar.slider("Maximum Sentiment (more negative → lower)",
#                                   min_value=-1.0,
#                                   max_value=0.0,
#                                   value=-0.4,
#                                   step=0.05)
# 
# channel_opts = st.sidebar.multiselect(
#     "Channel",
#     options=df["channel_name"].dropna().unique(),
#     default=df["channel_name"].dropna().unique().tolist()
# )
# 
# # ---- Apply filters ----------------------------------------------------
# filtered = df[
#     (df["Item_price"] > price_min) &
#     (df["sentiment_score"] < sentiment_max) &
#     (df["channel_name"].isin(channel_opts))
# ]
# 
# st.subheader(f"📊 {len(filtered)} flagged rows (out of {len(df)} total)")
# 
# # ---- Table ------------------------------------------------------------
# cols_to_show = [
#     "Unique id", "Order_id", "order_date_time",
#     "Customer Remarks", "sentiment_score", "Item_price",
#     "synthetic_amount", "synthetic_merchant",
#     "channel_name", "CSAT Score"
# ]
# 
# st.dataframe(filtered[cols_to_show].reset_index(drop=True),
#              height=400,
#              use_container_width=True)
# 
# # ---- Quick metrics ----------------------------------------------------
# st.subheader("💡 Quick Insights")
# col1, col2, col3 = st.columns(3)
# 
# col1.metric("Avg. Item Price", f"${filtered['Item_price'].mean():,.0f}")
# col2.metric("Avg. Synthetic Amount", f"${filtered['synthetic_amount'].mean():,.0f}")
# col3.metric("Mean Sentiment", f"{filtered['sentiment_score'].mean():.2f}")
# 
# # ---- Scatter chart ----------------------------------------------------
# st.subheader("📈 Amount vs. Sentiment")
# chart_data = filtered[["Item_price", "synthetic_amount", "sentiment_score"]]
# st.scatter_chart(chart_data.rename(columns={
#     "Item_price": "Real Amount",
#     "synthetic_amount": "Synthetic Amount",
#     "sentiment_score": "Sentiment"
# }))
# 
# # ---- Download button -------------------------------------------------
# csv_bytes = filtered.to_csv(index=False).encode()
# st.download_button(
#     label="💾 Download filtered rows (CSV)",
#     data=csv_bytes,
#     file_name="flagged_filtered.csv",
#     mime="text/csv"
# )